[project]
name = "advent-of-fpga"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["maturin>=1.11.5", "pytest>=9.0.2", "pytest-xdist>=3.8.0"]

[tool.pytest.ini_options]
addopts = "--tb=short"
testpaths = ["python"]
